const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const EDIT_TODO = 'EDIT_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';


export {
    ADD_TODO,
    REMOVE_TODO,
    EDIT_TODO,
    COMPLETE_TODO
}