//Todos
const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const EDIT_TODO = 'EDIT_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const FAVORITE_TODO = 'FAVORITE_TODO';
const ADD_NOTE = 'ADD_NOTE';
const ADD_TODO_LIST_CATEGORY = 'ADD_TODO_LIST_CATEGORY';
const ADD_TODO_DUE_DATE = 'ADD_TODO_DUE_DATE';
const FILTER_TODOS = 'FILTER_TODOS';
const ORDER_TODOS_BY_DATE_CREATED = 'ORDER_TODOS_BY_DATE_CREATED';
const ORDER_TODOS_ALPHABETICALLY = 'ORDER_TODOS_ALPHABETICALLY';
const ORDER_TODOS_BY_FAVORITES = 'ORDER_TODOS_BY_FAVORITES';
const REMOVE_TODO_LIST_CATEGORY = 'REMOVE_TODO_LIST_CATEGORY';
const EDIT_TODO_LIST_CATEGORY = 'EDIT_TODO_LIST_CATEGORY';

//Todolists
const ADD_TODO_LIST = 'ADD_TODO_LIST';
const REMOVE_TODO_LIST = 'REMOVE_TODO_LIST ';
const EDIT_TODO_LIST = 'EDIT_TODO_LIST';

//Theme
const TOGGLE_THEME_BUTTON = 'TOGGLE_THEME';

//EmojiSaga
const GET_EMOJIS_REQUESTED = 'GET_EMOJIS_REQUESTED';
const GET_EMOJIS_SUCCESS = 'GET_EMOJIS_SUCCESS';
const GET_EMOJIS_FAILED = 'GET_EMOJIS_FAILED';

export {
  ADD_TODO,
  REMOVE_TODO,
  EDIT_TODO,
  COMPLETE_TODO,
  FAVORITE_TODO,
  ADD_NOTE,
  ADD_TODO_LIST_CATEGORY,
  REMOVE_TODO_LIST_CATEGORY,
  EDIT_TODO_LIST_CATEGORY,
  ADD_TODO_DUE_DATE,
  FILTER_TODOS,
  ORDER_TODOS_BY_DATE_CREATED,
  ORDER_TODOS_ALPHABETICALLY,
  ORDER_TODOS_BY_FAVORITES,
  ADD_TODO_LIST,
  REMOVE_TODO_LIST,
  EDIT_TODO_LIST,
  TOGGLE_THEME_BUTTON,
  GET_EMOJIS_REQUESTED,
  GET_EMOJIS_SUCCESS,
  GET_EMOJIS_FAILED,
};
